### ISSUE TITLE
Control tracing with a decorator

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#223]
There are a couple of scenarios where it might be useful to change the tracing from within the code.

1. If we add a command-line version of the code tracer, it could be used as a debugging tool. However, you'd probably only want to trace one or two methods instead of the whole file. We could use a decorator like [PySnooper] does to select which methods to trace. It might also be nice to be able to trace code without having to install one of the plugins. Tracing a couple of functions might also make sense if they are called within a large program. You could even call the command-line version with `watch` to update the trace whenever you save a file, so it's sort of like live coding without the IDE integration.
2. Within one of the plugins, you might want to tell it not to trace some of the variables. Long variables like lists or strings can make loop displays harder to read.

[PySnooper]: https://github.com/cool-RR/PySnooper

Here's an example:

    import code_tracer       | 
                             | 
                             | 
    @code_tracer.trace_code  | 
    def foo(n):              | n = 3 
        s = 'x'              | s = 'x' 
        for i in range(n):   | i = 0    | i = 1     | i = 2 
            s += 'y'         | s = 'xy' | s = 'xyy' | s = 'xyyy' 
        return s             | return 'xyyy' 
                             | 
                             | 
    def bar(n):              |
        s = 'a'              |
        for i in range(n):   |
            s += 'b'         |
                             | 
                             | 
    print(foo(3))            |
    print(bar(3))            |

Possible features (probably move most to separate issues):

* [x] Move Python files into a package, with a `setup.py` file.
* [x] Mark a method to be the only section that gets traced.
* [x] Replace first positional argument with `--source`: "file to read the traced module from, or `-` for stdin. Defaults to standard Python loading."
* [x] Replace second positional argument with `--trace_module`: "module to display trace for. Defaults to `__main__`"
* [x] Add `--live` option: "load main module as `__live_coding__` instead of `__main__`."
* [x] Refactor top level code tracer to simplify it.
* [x] Fix alignment when `@traced` is used in the editor.
* [x] Add `--traced` option to select module or method
* [x] ~~Add `--stdin` option: "file to read stdin from, or - for normal stdin. Defaults to /dev/null."~~ moved to #238.
* [x] ~~Add `--stdout` option: "file to write stdout to (not tracing), or - for normal stdout. Defaults to /dev/null."~~ moved to #238.
* [x] ~~Add `--stderr` option: "file to write stderr to, or ! for normal stderr. Defaults to /dev/null."~~ moved to #238.
* [x] ~~Add `--report` option: "file to write tracing to, or - for stdout, or ! for stderr. Defaults to -."~~ moved to #238.
* [x] Replace `--dump` with `--source_width` option: "Width of source code - use 0 to hide or negative numbers to trim columns from the end, -1 to fit source code. Defaults to -1."
* [x] Add `--source_indent` option: "Number of spaces to indent source code. Negative to skip first columns of source code. Defaults to 0."
* [x] Add `trace_width` option: "number of columns to display, including source code. Use negative numbers to trim columns from the end, 0 for no limit." Defaults to display width? One less?
* [x] ~~Add `--trace_offset` option: "number of columns to skip at start of tracing display."~~ moved to #239.
* [x] ~~Add `--hide` option: "variable name to hide from display." Also allow `hide` parameter in decorator.~~ moved to #239.
* [x] ~~Add `--start_line` and `--end_line` options: "first/last line to trace in trace_module." Also allow `start_line` and `end_line` parameters in decorator.~~ moved to #239.
* [x] ~~Mark a section with a `with` block.~~ moved to #239.
* [x] ~~Add `--depth` option: "trace the methods that the marked method calls, within the same file, up to the given depth."~~ moved to #240.
* [x] `--live` and `--traced=__live_coding__` are incompatible with Pyglet, because the `__main__` module gets deleted?
* [x] publish the package on pypi

**Comment by Derfies** [comment]
I would like to help with this issue if possible. The decorated function’s code could be sent via a port to another process running an event loop with costly init / setup code.

**Comment by donkirkby** [comment]
Sounds great, @Derfies. I laid out the tasks in the order I thought made sense. I think we'll probably have to come up with a better name for the package and decorator, but we can start with what we have.

Do you think you would ever use a command-line version of the code tracer, or would you just use the decorator to control the tracing in your IDE?

If you want to discuss some detailed design plans, start a pull request with a bunch of comments in it, and mark it as in-progress.

**Comment by donkirkby** [comment]
In order to import the decorator and install the command-line version, I think we should publish a package on PyPI. I've created `setup.py` files for projects before, but I've never published anything on PyPI. Have you, @Derfies?

Any thoughts on naming? I'm thinking the package could be named `live_coding`, and the decorator could be named `traced`.

**Comment by donkirkby** [comment]
Now I'm thinking of calling the package `space_tracer`, because you trade time for space when you debug with it.

The decorator would look like this:

    # foo.py
    from space_tracer import traced


    @traced
    def foo(n):
        s = 'x'
        for i in range(n):
            s += 'y'
        return s


    def bar(n):
        s = 'a'
        for i in range(n):
            s += 'b'


    print(foo(3))
    print(bar(3))

Then you could run the command-line version like this:

    $ space_tracer foo.py
    def foo(n):            | n = 3 
        s = 'x'            | s = 'x' 
        for i in range(n): | i = 0    | i = 1     | i = 2 
            s += 'y'       | s = 'xy' | s = 'xyy' | s = 'xyyy' 
        return s           | return 'xyyy'

**Comment by donkirkby** [comment]
I've committed a bare minimum version, @Derfies. I'd love it if you could try out the [install instructions] on Windows. If you're still interested in helping, we could split up the remaining features between us.

**Comment by donkirkby** [comment]
The branch can be merged into master after PR melpa/melpa#6211 gets merged. It fixes the Emacs build to pull the new package folder instead of just a bunch of `.py` files.

**Comment by donkirkby** [comment]
I updated the top comment with my ideas for the new command-line arguments to make it work better as a command-line tool. The biggest change is loading the main module as `__main__` instead of `__live_coding__`. I think I might run the live coding plugins with the `--live` option that continues to load the main module as `__live_coding__`. That way users can write code like this:

    if __name__ == '__main__':
        launch_large_job()
    elif __name__ == '__live_coding__':
        launch_small_job()

That's easier than forcing them to use unit tests or driver scripts to call `launch_small_job()`, right?

**Comment by donkirkby** [comment]
Useful reference for loading a module, method, or function from a string: [`unittest.loader.TestLoader.loadTestsFromName()`].

[`unittest.loader.TestLoader.loadTestsFromName()`]: https://github.com/python/cpython/blob/b3ca7972c8d8c6479b6542ce28e0f7a6ebd5b8fe/Lib/unittest/loader.py#L138

**Comment by donkirkby** [comment]
Consider passing configuration details with environment variables. That way, the code that's being traced can set options, or the command line can get its defaults from environment variables. Could even set callbacks by putting a function name in an environment variable. For example, to pass an image to display on the canvas.

**Comment by donkirkby** [comment]
Reopening to publish the package on pypi.
