### ISSUE TITLE
New video for version 4

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/live-py-plugin#242]
I don't think the current video includes the matplotlib stuff, and it definitely doesn't include Sublime Text support, Pyglet, or the command-line version. Possibly separate videos for each version with links between?

Notes on tools to use and settings are in issue #90.

* [x] [Emacs]
* [x] ~~Space Tracer~~ split into issue #282.
* [x] ~~Sublime Text~~ split into issue #283
* [x] ~~PyCharm~~ split into issue #281

[Emacs]: https://youtu.be/aRmUiTPVnNg

**Comment by donkirkby** [comment]
Here are the settings and tools that I found useful this time.

Here's a command line for launching recordMyDesktop at 720p resolution:

    recordmydesktop -x 350 -y 100 --width 1280 --height 720  --delay 5 -o live-py.ogv

Stop recording with <kbd>Ctrl</kbd>+<kbd>C</kbd>, and edit sections together with a [moviepy] script.

[moviepy]: https://pypi.python.org/pypi/moviepy.

To check the position of the window, use `xwininfo`. I was using these coordinates:

    Emacs in terminal:
    Absolute upper-left X:  322
    Absolute upper-left Y:  63
    Width: 1340
    Height: 791

    PyCharm:
    Absolute upper-left X:  343
    Absolute upper-left Y:  99
    Width: 1295
    Height: 727

**Comment by donkirkby** [comment]
Next time, the Emacs display might be easier to see with Solarized light colour scheme.

Here's the moviepy script I used to splice all the video clips together.

    from pathlib import Path
    
    from moviepy.editor import VideoFileClip, concatenate_videoclips, afx
    
    raw_path = Path.home() / 'Videos' / 'live-py'
    raw_clips = [VideoFileClip(str(raw_path / 'emacs01-intro.ogv')).subclip(5, 24),
                 VideoFileClip(str(raw_path / 'emacs02-bad-search.ogv')).subclip(5, 152),
                 VideoFileClip(str(raw_path / 'emacs03-mid.ogv')).subclip(5, 112),
                 VideoFileClip(str(raw_path / 'emacs04-left.ogv')).subclip(5, 122),
                 VideoFileClip(str(raw_path / 'emacs05-right.ogv')).subclip(5, 137),
                 VideoFileClip(str(raw_path / 'emacs06-missing.ogv')).subclip(5, 120),
                 VideoFileClip(str(raw_path / 'emacs07-guard.ogv')).subclip(5, 77)]
    
    # noinspection PyUnresolvedReferences
    audio_normalize = afx.audio_normalize
    final_clip = concatenate_videoclips([clip.fx(audio_normalize)
                                         for clip in raw_clips])
    final_clip.write_videofile(str(raw_path / 'final.mp4'),
                               fps=15,
                               bitrate='3000k')
    print('Done.')
